# Generated by Django 5.0.1 on 2024-01-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название отделения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='images/icons/', verbose_name='Иконка отделения')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('photo', models.ImageField(upload_to='images/photos/', verbose_name='Фото')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.departament', verbose_name='Отделение')),
            ],
        ),
    ]
