# Generated by Django 5.0.1 on 2024-01-18 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='info',
            field=models.TextField(default='', verbose_name='Информация об образовании и аккредитации'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
        ),
    ]
