# Generated by Django 5.0.1 on 2024-01-20 11:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_employee_info_employee_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок страницы')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Контент страницы')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='info',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Информация об образовании и аккредитации'),
        ),
    ]
