# Generated by Django 5.0.1 on 2024-01-20 12:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_page_alter_employee_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вакансии')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Описание вакансии')),
            ],
        ),
    ]
