# Generated by Django 5.0.1 on 2024-01-20 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_page_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.departament', verbose_name='Отделение'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/photos/', verbose_name='Фото'),
        ),
    ]
