# Generated by Django 5.0.1 on 2024-01-24 09:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_employee_departament_alter_employee_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок статьи')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/pages/', verbose_name='Изображение')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Контент статьи')),
            ],
        ),
    ]
