# Generated by Django 5.0.1 on 2024-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
