# Generated by Django 5.0.1 on 2024-03-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_alter_sale_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/partners/', verbose_name='Логотип')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Ссылка на партнера')),
            ],
        ),
    ]
