# Generated by Django 5.0.1 on 2024-03-26 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_end',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 26)),
        ),
        migrations.AddField(
            model_name='sale',
            name='date_start',
            field=models.DateField(blank=True, default=datetime.date(2024, 3, 26)),
        ),
    ]
